accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('accounts/', include('accounts.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all blogs
    path('blogs/', views.blogs, name='blogs'),
    # Detail page for a single blog
    path('blogs/<int:blog_id>/', views.blog, name='blog'),
    # Page for adding a new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page for adding a new post
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing a post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    """A blog for making posts."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Post(models.Model):
    """A single blog post."""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'posts'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

blogs/forms.py
from django import forms

from .models import Blog, Post


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['text']
        labels = {'text': ''}


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display a blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Blog, Post
from .forms import BlogForm, PostForm


def index(request):
    """The home page for Blog."""
    return render(request, 'blogs/index.html')


@login_required
def blogs(request):
    """Shows all blogs."""
    blogs = Blog.objects.filter(owner=request.user).order_by('date_added')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)


@login_required
def blog(request, blog_id):
    """Shows a single blog and all its posts."""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request)
    posts = blog.post_set.order_by('-date_added')
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)


@login_required
def new_blog(request):
    """Adds a new blog."""
    if request.method != 'POST':  # user is requesting a blank form
        # No data submitted; create a blank form.
        form = BlogForm()
    else:
        # POST data submitted; process data.
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('blogs:blogs')
    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)


@login_required
def new_post(request, blog_id):
    """Adds a new post for a particular blog."""
    blog = Blog.objects.get(id=blog_id)
    check_blog_owner(blog, request)

    if request.method != 'POST':  # user is requesting a blank form
        # No data submitted; create a blank form.
        form = PostForm()
    else:
        # POST data submitted; process data.
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)
    # Display a blank or invalid form.
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Edits an existing post."""
    post = Post.objects.get(id=post_id)
    blog = post.blog
    check_blog_owner(blog, request)

    if request.method != 'POST':
        # Initial request, pre-fill form with the current post
        form = PostForm(instance=post)
    else:
        # POST data submitted and process data
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id=blog.id)

    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)


def check_blog_owner(blog, request):
    """Checks of the current user is the owner of the requested page."""
    if blog.owner != request.user:
        raise Http404

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        <div class="container-fluid">
            <p>
                <a class="navbar-brand" href="{% url 'blogs:index' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=""
                    #navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <!--Links on left side of navbar-->
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blogs:blogs' %}">Blogs</a>
                    </li>
                </ul> <!--End of links on left side of navbar-->
                <!--Account related links-->
                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">Hello, {{ user.username }}.</span>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul> <!--End of account related links-->
                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button name="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                </form>
                {% endif %}
            </div> <!--Closes collapsible parts of navbar-->
        </div> <!--Closes navbar's container-->
    </nav> <!--End of navbar-->
    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<h1>{{ blog.text }}</h1>
{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'blogs:new_post' blog.id %}">Add new post</a>
</p>

{% for post in posts %}
<div class="card mb-3">
    <!--Card header with timestamp and edit link-->
    <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        <small>
            <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
        </small>
    </h4>
    <!--Card body with post text-->
    <div class="card-body">{{ post.text|linebreaks }}</div>
</div>
{% empty %}
<p>There are no posts for this blog.</p>
{% endfor %}
{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<h1>Blogs</h1>
{% endblock page_header %}

{% block content %}
<ul class="list-group border-bottom pb-2 mb-4">
    {% for blog in blogs %}
    <li class="list-group-item border-0">
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog.text }}</a>
    </li>
    {% empty %}
    <li class="list-group-item border-0">No blogs have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Edit post:</h2>
{% endblock page_header %}

{% block content %}
<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>
<form action="{% url 'blogs:edit_post' post.id %}" method="post">
    {% csrf_token %} <!--cross-site request forgery-->
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save changes" %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
<div class="p-3 mb-4 bg-dark text-white border rounded-3">
    <div class="container-fluid py-4">
        <h1 class="display-3">Start your own personal blog.</h1>
        <p class="lead">Blog is problem 19-1 of Python Crash Course (3rd Edition) by Eric Matthes.<br>
            It is continued in chapter 20, where more functionality and styling is added.</p>
        <a class="btn btn-primary btn-lg mt-1" href="{% url 'accounts:register' %}">Register &raquo;</a>
    </div>
</div>
{% endblock page_header %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Add a new blog:</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'blogs:new_blog' %}" method="post">
    {% csrf_token %} <!--cross-site request forgery-->
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add blog" %}
</form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}
<h2>Add a new post:</h2>
{% endblock page_header %}

{% block content %}
<p><a href="{% url 'blogs:blog' blog.id %}">{{ blog }}</a></p>
<form action="{% url 'blogs:new_post' blog.id %}" method="post">
    {% csrf_token %} <!--cross-site request forgery-->
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add post" %}
</form>

{% endblock content %}